import 'package:flutter/material.dart';

import '../../theme/tokens.dart';

/// Mockup-only markdown stub shown behind the ink overlay. Real markdown
/// rendering is a later task (`MarkdownRenderer` — IMPLEMENTATION.md §4.4);
/// T7 keeps this stub so the canvas still looks like the PRD mockup when
/// browsed inside the mockup shell.
class MarkdownStub extends StatelessWidget {
  const MarkdownStub({super.key});

  @override
  Widget build(BuildContext context) {
    final t = context.tokens;
    final h1 = TextStyle(
      color: t.textPrimary,
      fontSize: 26,
      fontWeight: FontWeight.w700,
      height: 1.25,
    );
    final h2 = TextStyle(
      color: t.textPrimary,
      fontSize: 18,
      fontWeight: FontWeight.w600,
      height: 1.3,
    );
    final body = TextStyle(
      color: t.textPrimary,
      fontSize: 14,
      height: 1.7,
    );
    final meta = TextStyle(color: t.textMuted, fontSize: 11);

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text('Auth flow \u2014 TOTP rollout', style: h1),
        const SizedBox(height: 6),
        Text('Generated by Claude Code on 2026-04-19', style: meta),
        const SizedBox(height: 20),
        Text('Open questions', style: h2),
        const SizedBox(height: 8),
        Text(
          'Q1: Should auth flow support magic links as primary, or only as '
          'fallback after TOTP?',
          style: body,
        ),
        Text(
          'Q2: Do we expire the session-cookie grace period at 7 or 14 days?',
          style: body,
        ),
        Text(
          'Q3: Session store \u2014 assume Redis, or read from config?',
          style: body,
        ),
        Text(
          'Q4: Do we rate-limit TOTP attempts per account or per IP?',
          style: body,
        ),
        const SizedBox(height: 20),
        Text('Assumptions', style: h2),
        const SizedBox(height: 8),
        Text('Default session store will remain Redis.', style: body),
        Text(
          'TOTP apps supported: Google Authenticator, 1Password, Authy.',
          style: body,
        ),
        Text(
          'Migration is transparent; no user-visible downtime.',
          style: body,
        ),
      ],
    );
  }
}
